export const bikesCatalogue = [
  {
    id: 1,
    new: true,
    brand: "Lapierre",
    model: "Overvolt",
    price: 2991,
    promo: true,
    pricePromo: 2491,
    sold: false,
    messagePerso: "",
    description : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reprehenderit aperiam, nisi nobis iure quos rerum!",

    numberSpeeds: "1 x 12",
    transmission: "Shimano XT",
    size: "L",
    wheelsType: "29",
    wheels:"Mavic Crossmax",
    
    brake : "Shimano XT",
    typeBike: "VTT",
    suspension: "Full suspension",
    electric: true,
    detail : "Bosh , 625Wh",
    picture:
      "/images/bikes/bikeKiki.png",
  },
  {
    id: 2,
    new: false,
    brand: "Lapierre2",
    model: "Overvolt2",
    price: 2992,
    promo: true,
    pricePromo: 24992,
    sold: false,
    messagePerso: "",
    numberSpeeds: "1 x 12",
    transmission: "Shimano XT2",
    size: "L2",
    wheels: "29",
    typeBike: "VTT",
    suspension: "Full suspension",
    picture:
    "/images/bikes/bikeKiki.png",
  },
  {
    id: 3,
    new: false,
    brand: "Lapierre3",
    model: "Overvolt3",
    price: 2993,
    promo: true,
    pricePromo: 24993,
    sold: false,
    messagePerso: "",
    numberSpeeds: "1 x 13",
    transmission: "Shimano XT3",
    size: "L",
    wheels: "29",
    typeBike: "VTT",
    suspension: "Full suspension",
    picture:
    "/images/bikes/bikeKiki.png",
  },
  {
    id: 4,
    new: true,
    brand: "Lapierr4 ",
    model: "Overvol4 ",
    price: 2994 ,
    promo: true,
    pricePromo: 2494,
    sold: false,
    messagePerso: "",
    numberSpeeds: "1 x 14",
    transmission: "Shimano X4",
    size: "L",
    wheels: "29",
    typeBike: "VTT",
    suspension: "Full suspension",
    picture:
    "/images/bikes/bikeKiki.png",
  },
  {
    id: 5,
    new: true,
    brand: "Lapierre5",
    model: "Overvolt5",
    price: 29995,
    promo: true,
    pricePromo: 24995,
    sold: false,
    messagePerso: "",
    numberSpeeds: "1 x 125",
    transmission: "Shimano XT5",
    size: "L",
    wheels: "29",
    typeBike: "VTT",
    suspension: "Full suspension",
    picture:
    "/images/bikes/bikeKiki.png",
  },
  {
    id: 6,
    new: true,
    brand: "Lapierre6",
    model: "Overvolt6",
    price: 29996,
    promo: false,
    pricePromo: 24996,
    sold: false,
    messagePerso: "",
    numberSpeeds: "1 x 126",
    transmission: "Shimano XT6",
    size: "L",
    wheels: "29",
    typeBike: "VTT",
    suspension: "Full suspension",
    picture:
    "/images/bikes/bikeKiki.png",
  },
  {
    id: 7,
    new: true,
    brand: "Lapierre7",
    model: "Overvolt7",
    price: 29997,
    promo: true,
    pricePromo: 24997,
    sold: false,
    messagePerso: "",
    numberSpeeds: "1 x 127",
    transmission: "Shimano XT7",
    size: "L",
    wheels: "29",
    typeBike: "VTT",
    suspension: "Full suspension",
    picture:
    "/images/bikes/bikeKiki.png",
  },
  {
    id: 8,
    new: false,
    brand: "Lapierre8",
    model: "Overvolt8",
    price: 29998,
    promo: true,
    pricePromo: 24998,
    sold: false,
    messagePerso: "",
    numberSpeeds: "1 x 128",
    transmission: "Shimano XT8",
    size: "L",
    wheels: "29",
    typeBike: "VTT",
    suspension: "Full suspension",
    picture:
    "/images/bikes/bikeKiki.png",
  },
  {
    id: 9,
    new: false,
    brand: "Lapierre9",
    model: "Overvolt9",
    price: 29999,
    promo: true,
    pricePromo: 24999,
    sold: false,
    messagePerso: "",
    numberSpeeds: "1 x 129",
    transmission: "Shimano XT9",
    size: "L",
    wheels: "29",
    typeBike: "VTT",
    suspension: "Full suspension",
    picture:
    "/images/bikes/bikeKiki.png",
  },
];